development:
  adapter: mysql2
  database: sehackday_dev
  username: local_user
  password: local_password

test:
  adapter: mysql2
  database: sehackday_test
  username: local_user
  password: local_password

production:
  adapter: mysql2
  database: sehackday_production
  username: production_user
  password: production_password
